routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [

    ],
    function () {
        Auth::routes(['register' => false]);
    }
);

Route::group(
    [
        'middleware' => [
            'auth',
        ],
    ],
    function () {
        Route::group(
            [
                'prefix' => 'items',
                'as' => 'items.',
                'namespace' => '\Admin\Item',
            ],
            function () {
                //items routes
                Route::get('', 'ItemController@index')->name('index');
                Route::get('/create', 'ItemController@create')->name('create');
                Route::post('', 'ItemController@store')->name('store');
                Route::get('/{item}/show', 'ItemController@show')->name('show');
                Route::get('/{item}/edit', 'ItemController@edit')->name('edit');
                Route::match(['put', 'patch'], '/{item}', 'ItemController@update')->name('update');
                Route::get('/{item}/delete', 'ItemController@destroy')->name('destroy');
            }
        );
        Route::group(
            [
                'prefix' => 'categories',
                'as' => 'categories.',
                'namespace' => '\Admin\Category',
            ],
            function () {
                //categories routes
                Route::get('', 'CategoryController@index')->name('index');
                Route::get('/create', 'CategoryController@create')->name('create');
                Route::post('', 'CategoryController@store')->name('store');
                //Route::get('/{category}', 'CategoryController@show')->name('show');
                Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
                Route::match(['put', 'patch'], '/{category}', 'CategoryController@update')->name('update');
                Route::get('/{category}/delete', 'CategoryController@destroy')->name('destroy');
            }
        );
    }
);

Route::group([
    'middleware' => ['cors'],
], function ($router) {

    Route::get('/{itemUUID}', 'Controller@getItemInformation')->name('item.view');
});

Route::any('/{any}', function () {
    return redirect()->route('items.index');
})->where('any', '.*');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- Material Dashboard CSS -->
    <link rel="stylesheet" href="{{asset('md4p/css/material-dashboard.min.css?v=2.1.1')}}">

    @yield('style')

</head>
<body>
    <div class="wrapper">
        @include('sidebar')
        <main class="c-main">
            <div class="main-panel ps-container ps-theme-default" data-ps-id="cb706d96-7f28-5236-d2fc-5ef09c121b52">
                @include('topnavbar')
                <div class="content">
                    @yield('content')
                </div>
            </div>
            <!-- Main content here -->
        </main>
    </div>

    <!--   Core JS Files   -->
    <script src="{{asset('md4p/js/core/jquery.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('md4p/js/core/popper.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('md4p/js/core/bootstrap-material-design.min.js')}}" type="text/javascript"></script>

    <!-- Plugin for the Perfect Scrollbar -->
    <script src="{{asset('md4p/js/plugins/perfect-scrollbar.jquery.min.js')}}"></script>

    <!-- Plugin for the momentJs  -->
    <script src="{{asset('md4p/js/plugins/moment.min.js')}}"></script>

    <!--  Plugin for Sweet Alert -->
    <script src="{{asset('md4p/js/plugins/sweetalert2.js')}}"></script>

    <!-- Forms Validations Plugin -->
    <script src="{{asset('md4p/js/plugins/jquery.validate.min.js')}}"></script>

    <!--  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
    <script src="{{asset('md4p/js/plugins/jquery.bootstrap-wizard.js')}}"></script>

    <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
    <script src="{{asset('md4p/js/plugins/bootstrap-selectpicker.js')}}" ></script>

    <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
    <script src="{{asset('md4p/js/plugins/bootstrap-datetimepicker.min.js')}}"></script>

    <!--  DataTables.net Plugin, full documentation here: https://datatables.net/    -->
    <script src="{{asset('md4p/js/plugins/jquery.datatables.min.js')}}"></script>

    <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
    <script src="{{asset('md4p/js/plugins/bootstrap-tagsinput.js')}}"></script>

    <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
    <script src="{{asset('md4p/js/plugins/jasny-bootstrap.min.js')}}"></script>

    <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
    <script src="{{asset('md4p/js/plugins/fullcalendar.min.js')}}"></script>

    <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
    <script src="{{asset('md4p/js/plugins/jquery-jvectormap.js')}}"></script>

    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="{{asset('md4p/js/plugins/nouislider.min.js')}}" ></script>

    <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>

    <!-- Library for adding dinamically elements -->
    <script src="{{asset('md4p/js/plugins/arrive.min.js')}}"></script>

    <!--  Google Maps Plugin    -->
    {{--<script  src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>--}}

    <!-- Chartist JS -->
    <script src="{{asset('md4p/js/plugins/chartist.min.js')}}"></script>

    <!--  Notifications Plugin    -->
    <script src="{{asset('md4p/js/plugins/bootstrap-notify.js')}}"></script>

    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="{{asset('md4p/js/material-dashboard.min.js?v=2.1.1')}}" type="text/javascript"></script>

    @yield('js')

</body>
</html>

resources/views/pdf_layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    @yield('css')
</head>
<body>
    @yield('content')
</body>
</html>

resources/views/sidebar.blade.php
<div class="sidebar" data-color="purple" data-background-color="black" data-image="{{asset('md4p/img/sidebar-1.jpg')}}">
    <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->
    <div class="logo">
        <a href="{{route('items.index')}}" class="simple-text logo-normal text-center">
            {{ config('app.name', 'Laravel') }}
        </a>
    </div>
    <div class="sidebar-wrapper ps-container ps-theme-default" data-ps-id="ea1a47fa-01a7-3e48-938c-923988e00230">
        @php $routeName = \Request::route()->getName(); @endphp
        <ul class="nav">

            <li class="nav-item @if (strpos($routeName, 'items') !== false) active @endif">
                <a class="nav-link" href="{{route('items.index')}}">
                    <i class="material-icons">apartment</i>
                    <p>Items</p>
                </a>
            </li>
            <li class="nav-item @if (strpos($routeName, 'categories') !== false) active @endif">
                <a class="nav-link" href="{{route('categories.index')}}">
                    <i class="material-icons">folder_special</i>
                    <p>Categories</p>
                </a>
            </li>
        </ul>
        <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;">
            <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;">
            </div>
        </div>
        <div class="ps-scrollbar-y-rail" style="top: 0px; right: 0px;">
            <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;">
            </div>
        </div>
    </div>
</div>

resources/views/topnavbar.blade.php
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-just-icon btn-white btn-fab btn-round">
                    <i class="material-icons text_align-center visible-on-sidebar-regular">more_vert</i>
                    <i class="material-icons design_bullet-list-67 visible-on-sidebar-mini">view_list</i>
                    <div class="ripple-container"></div></button>
            </div>
            @php
                $routeName = \Request::route()->getName();
                if (strpos($routeName, 'items') !== false)
                {
                    $brand = 'Items';
                }
                else if (strpos($routeName, 'categories') !== false)
                {
                    $brand = 'Categories';
                }
                else
                {
                    $brand = config('app.name', 'Laravel');
                }
            @endphp
            <a class="navbar-brand" href="#pablo">{{$brand}}</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        {{--<a class="dropdown-item" href="#">Profile</a>--}}
                        {{--<a class="dropdown-item" href="#">Settings</a>--}}
                        {{--<div class="dropdown-divider"></div>--}}
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

@section('js')
    {{--<script type="text/javascript">--}}
        {{--$(document).ready(function () {--}}
            {{--$('#minimizeSidebar').on('click', function () {--}}
                {{--console.log('asdf');--}}
                {{--alert('click');--}}
                {{--$('[id$="-datatable"]').DataTable().columns.adjust().draw();--}}
                {{--console.log($('[id$="-datatable"]'));--}}
            {{--});--}}
        {{--});--}}
    {{--</script>--}}
@endsection
<!-- End Navbar -->

resources/views/user_layout.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />

    <!-- CSRF Token -->
{{--    <meta name="csrf-token" content="{{ csrf_token() }}">--}}

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- Material Dashboard CSS -->
    <link rel="stylesheet" href="{{asset('md4p/css/material-dashboard.min.css?v=2.1.1')}}">

    <style>
        .custom-user-perspective{
            width: 100%;
            margin-top:0;
        }
    </style>
    @yield('style')

</head>
<body>
<div class="wrapper">
    <main class="c-main">
        <div class="main-panel ps-container ps-theme-default custom-user-perspective" data-ps-id="cb706d96-7f28-5236-d2fc-5ef09c121b52">
            <div class="content">
                @yield('content')
            </div>
        </div>
        <!-- Main content here -->
    </main>
</div>

<!--   Core JS Files   -->
<script src="{{asset('md4p/js/core/jquery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('md4p/js/core/popper.min.js')}}" type="text/javascript"></script>
<script src="{{asset('md4p/js/core/bootstrap-material-design.min.js')}}" type="text/javascript"></script>

<!-- Plugin for the Perfect Scrollbar -->
<script src="{{asset('md4p/js/plugins/perfect-scrollbar.jquery.min.js')}}"></script>

<!-- Plugin for the momentJs  -->
<script src="{{asset('md4p/js/plugins/moment.min.js')}}"></script>

<!--  Plugin for Sweet Alert -->
<script src="{{asset('md4p/js/plugins/sweetalert2.js')}}"></script>

<!-- Forms Validations Plugin -->
<script src="{{asset('md4p/js/plugins/jquery.validate.min.js')}}"></script>

<!--  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
<script src="{{asset('md4p/js/plugins/jquery.bootstrap-wizard.js')}}"></script>

<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
<script src="{{asset('md4p/js/plugins/bootstrap-selectpicker.js')}}" ></script>

<!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
<script src="{{asset('md4p/js/plugins/bootstrap-datetimepicker.min.js')}}"></script>

<!--  DataTables.net Plugin, full documentation here: https://datatables.net/    -->
<script src="{{asset('md4p/js/plugins/jquery.datatables.min.js')}}"></script>

<!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
<script src="{{asset('md4p/js/plugins/bootstrap-tagsinput.js')}}"></script>

<!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{{asset('md4p/js/plugins/jasny-bootstrap.min.js')}}"></script>

<!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
<script src="{{asset('md4p/js/plugins/fullcalendar.min.js')}}"></script>

<!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
<script src="{{asset('md4p/js/plugins/jquery-jvectormap.js')}}"></script>

<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{{asset('md4p/js/plugins/nouislider.min.js')}}" ></script>

<!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>

<!-- Library for adding dinamically elements -->
<script src="{{asset('md4p/js/plugins/arrive.min.js')}}"></script>

<!--  Google Maps Plugin    -->
{{--<script  src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>--}}

<!-- Chartist JS -->
<script src="{{asset('md4p/js/plugins/chartist.min.js')}}"></script>

<!--  Notifications Plugin    -->
<script src="{{asset('md4p/js/plugins/bootstrap-notify.js')}}"></script>

<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{{asset('md4p/js/material-dashboard.min.js?v=2.1.1')}}" type="text/javascript"></script>

@yield('js')


</body>
</html>