routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [

    ],
    function () {
        Auth::routes(['register' => false]);
    }
);

Route::group(
    [
        'middleware' => [
            'auth',
        ],
    ],
    function () {
        Route::group(
            [
                'prefix' => 'items',
                'as' => 'items.',
                'namespace' => '\Admin\Item',
            ],
            function () {
                //items routes
                Route::get('', 'ItemController@index')->name('index');
                Route::get('/create', 'ItemController@create')->name('create');
                Route::post('', 'ItemController@store')->name('store');
                Route::get('/{item}/show', 'ItemController@show')->name('show');
                Route::get('/{item}/edit', 'ItemController@edit')->name('edit');
                Route::match(['put', 'patch'], '/{item}', 'ItemController@update')->name('update');
                Route::get('/{item}/delete', 'ItemController@destroy')->name('destroy');
            }
        );
        Route::group(
            [
                'prefix' => 'categories',
                'as' => 'categories.',
                'namespace' => '\Admin\Category',
            ],
            function () {
                //categories routes
                Route::get('', 'CategoryController@index')->name('index');
                Route::get('/create', 'CategoryController@create')->name('create');
                Route::post('', 'CategoryController@store')->name('store');
                //Route::get('/{category}', 'CategoryController@show')->name('show');
                Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
                Route::match(['put', 'patch'], '/{category}', 'CategoryController@update')->name('update');
                Route::get('/{category}/delete', 'CategoryController@destroy')->name('destroy');
            }
        );
    }
);

Route::group([
    'middleware' => ['cors'],
], function ($router) {

    Route::get('/{itemUUID}', 'Controller@getItemInformation')->name('item.view');
});

Route::any('/{any}', function () {
    return redirect()->route('items.index');
})->where('any', '.*');

app/Http/Controllers/Admin/Item/Item.php
<?php
/**
 * Created by PhpStorm.
 * User: Gabriel-Marian Hanci
 * Date: 21-Jan-20
 * Time: 0:03
 */

namespace App\Http\Controllers\Admin\Item;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;



class Item extends Model
{
    use SoftDeletes;

    protected $table = 'items';

    public $timestamps = true;

    protected $fillable = [
        'category_id',
        'name',
        'uuid',
        'page_title',
        'page_body',
        'image_path',
        'qr_code_path',
        'print_file_path',
    ];

    public function category()
    {
        return $this->belongsTo('App\Http\Controllers\Admin\Category\Category');
    }

    public function getPageBodyAttribute($value)
    {
        return htmlspecialchars_decode($value);
    }


}

app/Http/Controllers/Admin/Item/ItemController.php
<?php
/**
 * Created by PhpStorm.
 * User: Gabriel-Marian Hanci
 * Date: 18-Jan-20
 * Time: 23:42
 */

namespace App\Http\Controllers\Admin\Item;


use App\Http\Controllers\Controller;
use App\Http\Controllers\Admin\Item\ItemService;
use App\Http\Controllers\Admin\Category\CategoryService;
use Illuminate\Support\Facades\Cache;

class ItemController extends Controller
{

    protected $categoryService;
    protected $itemService;

    public function __construct(ItemService $itemService, CategoryService $categoryService)
    {
        $this->itemService = $itemService;
        $this->categoryService = $categoryService;
    }

    public function index()
    {
        $response = $this->itemService->all();
        return view('items.index')->with('items', $response);
    }

    public function edit(Item $item)
    {
        $response = $this->itemService->edit($item);
        $categories = $this->categoryService->all();

        return view('items.edit')
            ->with('item', $response)
            ->with('categories', $categories);
    }

    public function show(Item $item)
    {
        return view('items.show')->with('item', $item);
    }

    public function store(ItemValidator $request)
    {
        $item = $this->itemService->store($request);
        $status = true;
        $message = 'Item Created Successfully!';

        return redirect()->route('items.edit', [$item])
            ->with('status', $status)
            ->with('message', $message);
    }

    public function update(ItemValidator $request, Item $item)
    {
        $status = $this->itemService->update($request, $item);
        $message = 'Item Updated Successfully!';

        return redirect()->route('items.edit', [$item])
            ->with('status', $status)
            ->with('message', $message);
    }

    public function destroy(Item $item)
    {
        $status = $this->itemService->destroy($item);

        return redirect()->route('items.index')->with('status', $status)->with('message',"Item successfully deleted");
    }

    public function create()
    {
        $categories = $this->categoryService->all();
        return view('items.create')->with('categories', $categories);
    }
}

app/Http/Controllers/Admin/Item/ItemService.php
<?php
/**
 * Created by PhpStorm.
 * User: Gabriel-Marian Hanci
 * Date: 21-Jan-20
 * Time: 0:12
 */

namespace App\Http\Controllers\Admin\Item;


use App\Http\Controllers\Admin\Helpers;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Storage;
use QrCode, PDF;

class ItemService
{
    protected $itemModel;

    private $clientUrl = 'https://costica.dev/';

    public function __construct(Item $item)
    {
        $this->itemModel = $item;
    }

    public function all()
    {
        $response = $this->itemModel->all();
        return $response;
    }

    public function edit(Item $item)
    {
        return $this->itemModel->where('id', $item->id)->first();
    }

    /*
     * name, category_id, and page title can be straight updated, they're just plain text
     * image update must be handled individually before regenerating pdf (if needed)
     * if anything our pdf contains (page_title, image, page_body) changes, we must regenerate pdf
     * */
    public function update($request, Item $item)
    {
        $request = $request->all();

        /*
         * before updating, check if pdf must be regenerated
         * */
        $regeneratePDF = $this->PDFRegenerationRequired($request, $item);

        if (isset($request['image']))
        {
            $request['uuid'] = $item->uuid;
            $request['image_path'] = $this->storeImage($request);
        }

        $request = $this->removeUnnecessaryFields($request);

        /*
         * update whatever we have so far so we have latest data for the pdf regeneration
         * */
        $status = $item->update($request);
        $item->touch();

        /*
         * regenerate pdf based on latest data
         * we do not need to update the path cuz it's the same stuff
         * */
        if ($regeneratePDF)
        {
            $this->generateAndStoreItemPDF($item);
            $this->generateAndStoreQrCodePDF($item);
        }

        return $status;
    }

    public function destroy(Item $item)
    {
        return $item->delete();
    }

    public function PDFRegenerationRequired($request, $item)
    {
        $response = false;

        if ($request['page_title'] !== $item->page_title)
        {
            $response = true;
        }
        if ($request['page_body'] !== $item->page_body)
        {
            $response= true;
        }
        if (isset($request['image']))
        {
            $response = true;
        }

        return $response;
    }

    public function store($request)
    {
        $request = $request->all();

        $request = $this->generateFields($request);

        $request = $this->removeUnnecessaryFields($request);

        $item = $this->itemModel->create($request);
        return $item;
    }

    public function removeUnnecessaryFields($request)
    {
        $modelColumns = Schema::getColumnListing('items');

        foreach ($request as $column => $value)
        {
            if (!in_array($column, $modelColumns))
            {
                unset($request[$column]);
            }
        }

        return $request;
    }

    public function convertHTMLFields($request)
    {
        $request['page_body'] = htmlspecialchars($request['page_body']);
        return $request;
    }

    public function generateFields($request)
    {
        $uuid = $this->generateValidUUID(true);
        $request['uuid'] = $uuid;

        $qrCodePaths = $this->generateAndStoreQrCode($request, 'png');
        $request['qr_code_path'] = $qrCodePaths['path'];

        $imagePath = $this->storeImage($request);
        $request['image_path'] = $imagePath;

        $pdfPaths = $this->generateAndStoreItemPDF($request);
        $request['print_file_path'] = $pdfPaths['path'];

        $this->generateAndStoreQrCodePDF($request);

        return $request;
    }

    public function generateAndStoreQrCodePDF($item)
    {
        $response = [];

        $filename = $item['uuid'] . '_only_qr';
        $fullPath = Helpers::generatePDFStoragePath($filename, 'pdf');

        $response['fullPath'] = $fullPath;
        $response['path'] = Helpers::generatePDFPath($filename, 'pdf');

        /*
         * delete file if it already exists (this is for update item cases)
         * this is needed because the pdf composer package can't overwrite existing files
         * */
        $this->deleteFileIfExists($response['path']);

        $this->generateQrCodePDF($item)->save($fullPath);

        return $response;
    }

    public function generateAndStoreItemPDF($item)
    {
        $response = [];

        $filename = $item['uuid'];
        $fullPath = Helpers::generatePDFStoragePath($filename, 'pdf');

        $response['fullPath'] = $fullPath;
        $response['path'] = Helpers::generatePDFPath($filename, 'pdf');

        /*
         * delete file if it already exists (this is for update item cases)
         * this is needed because the pdf composer package can't overwrite existing files
         * */
        $this->deleteFileIfExists($response['path']);

        $this->generateItemPDF($item)->save($fullPath);

        return $response;
    }

    public function deleteFileIfExists($path)
    {
        $exists = Storage::disk('uploads')->exists($path);
        if ($exists)
        {
            Storage::disk('uploads')->delete($path);
        }
    }

    public function generateQrCodePDF($item)
    {
        $pdf = PDF::loadView('items.qrcode_pdf', [
            'item' => $item,
        ]);

        return $pdf;
    }

    public function generateItemPDF($item)
    {
        $pdf = PDF::loadView('items.qrcode_with_info_pdf', [
            'item' => $item,
        ]);

        return $pdf;
    }

    /*
     * returns [
     *  'fullPath' => full path to the file on the server
     *  'path' => relative path to public
     * ]the full path to the file on the server
     * */

    private function getQrUrl($uuid){
        return $this->clientUrl . $uuid;
    }

    public function generateAndStoreQrCode($item, $format = 'png')
    {
        $response = [];

        $uuid = $item['uuid'];

        $fullPath = Helpers::generateQrCodeStoragePath($uuid, $format);

        $response['fullPath'] = $fullPath;

        QrCode::errorCorrection('H')
            ->format($format)
            ->size(QR_CODE_SIZE)
            ->margin(QR_CODE_MARGINS)
            ->generate($this->getQrUrl($uuid), $fullPath);

        $response['path'] = Helpers::generateQrCodePath($uuid, $format);

        return $response;
    }

    public function generateValidUUID($ordered = false)
    {
        $uuid = null;

        $uuid = Helpers::generateUUID($ordered);

        while (Item::where('uuid', $uuid)->count() !== 0)
        {
            $uuid = Helpers::generateUUID($ordered);
        }

        return $uuid;
    }

    public function storeImage($request)
    {
        $path = null;

        //if an image has been uploaded in form
        if (isset($request['image']))
        {
            $storagePath = Helpers::generateImageStoragePath($request);
            $this->deleteFileIfExists($storagePath);
            $filename = Helpers::getUploadedImageFilename($request);
            $path = '/' . Storage::disk('uploads')->putFileAs(__DB__ITEM_IMAGE_PATH, $request['image'], $filename);
        }
        //else provide path to placeholder
        else
        {
            $path = PLACEHOLDER_DEFAULT_IMAGE_PATH;
        }

        return $path;
    }

    public function unbindCategoryItems($category)
    {
        $status = $this->itemModel->where('category_id', $category->id)
            ->update([
                'category_id' => DEFAULT_CATEGORY_ID,
            ]);

        return $status;
    }
}

app/Http/Controllers/Admin/Item/ItemValidator.php
<?php
/**
 * Created by PhpStorm.
 * User: Gabriel-Marian Hanci
 * Date: 24-Jan-20
 * Time: 19:25
 */

namespace App\Http\Controllers\Admin\Item;


use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ItemValidator extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        switch ($this->method())
        {
            case 'GET':
            case 'DELETE':
                {
                    return [];
                }
            case 'POST':
                {
                    return [
                        'name' => ['required', 'string', 'max:191', 'unique:items,name'],
                        'image' => ['image', 'mimes:jpeg,png,jpg', 'max:2048'],
                        'page_title' => ['string', 'max:191'],
                    ];
                }
            case 'PUT':
                {}
            case 'PATCH':
                {
                    $item = request()->item;
                    return [
                        'name' => ['required', 'string', 'max:191', Rule::unique('items', 'name')->ignore($item->id)],
                        'image' => ['image', 'mimes:jpeg,png,jpg', 'max:2048'],
                        'page_title' => ['string', 'max:191'],
                    ];
                }
            default:
                break;
        }
    }

    public function messages()
    {
        return [
            'name.required'     => 'A name is required.',
            'name.max'          => 'The name cannot have more than 191 characters',
            'name.unique'       => 'The name is already in use!',
            'image.mimes'       => 'The image must respect any of this formats:jpeg,png,jpg',
            'image.image'       => 'The uploaded file must be an image.',
            'image.max'         => 'Image size is too large.',
            'page_title.max'    => 'The title cannot have more than 191 characters',
        ];
    }


}

resources/views/items/create.blade.php
@extends('layout')

@section('style')
    <link href="https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />

    <style>
        .resize-image {
            height: 250px;
            margin-left: auto;
            margin-right: auto;
        }
        .card-text-right:hover {
            cursor: pointer;
        }
        .card-text-right {
            position: relative!important;
            float: right!important;
            /*margin-top: -28px!important;*/
        }
        .custom-error-cross {
            right: -35px!important;
        }
        .ml-20 {
            margin-left: 20px;
        }
    </style>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <form id="create-item-form" class="form-horizontal" action="{{route('items.store')}}" method="POST" novalidate="novalidate" enctype="multipart/form-data">
                    @csrf
                    <div class="card">
                        <div class="card-header card-header-primary card-header-text">
                            <div class="card-text">
                                <h4 class="card-title">Add a New Item</h4>
                            </div>
                            <div class="card-text card-text-right card-header-info" id="redirect-to-items-index">
                                <h4 class="card-title">Go Back</h4>
                            </div>
                            <a href="{{route('items.index')}}" class="btn btn-primary btn-round button-right d-none" id="items-index">Go Back</a>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <label class="col-sm-2 col-form-label" for="item-name">Name</label>
                                <div class="col-sm-7">
                                    <div class="form-group bmd-form-group @if ($errors->has('name')) has-danger @endif">
                                        <input class="form-control" value="{{old('name')}}" type="text" id="item-name" name="name" required="true" aria-required="true" aria-invalid="true">
                                        @if ($errors->has('name'))
                                            <span class="material-icons form-control-feedback custom-error-cross">clear</span>
                                                @foreach ($errors->get('name') as $key => $error)
                                                    <label id="name-error-{{$key}}" class="error" for="name"><strong>#{{++$key}}</strong> {{$error}}</label>
                                                @endforeach
                                        @endif
                                    </div>
                                </div>
                                <label class="col-sm-2 label-on-right ml-20">
                                    <code>required</code>
                                </label>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 col-form-label" for="item-category">Category</label>
                                <div class="col-sm-7">
                                    <div class="form-group">
                                        <select class="form-control selectpicker" data-style="btn btn-link" id="item-category" name="category_id">
                                            @foreach($categories as $category)
                                                <option value="{{$category->id}}" @if($category->id == old('category_id')) selected @endif>{{$category->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <label class="col-sm-2 label-on-right ml-20">
                                    <code>required</code>
                                </label>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 col-form-label">Image Preview</label>
                                <div class="col-sm-7">
                                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                                        <div class="carousel-inner">
                                            <div class="carousel-item active">
                                                <img class="d-block resize-image" src="{{asset('/uploads/items/img/placeholder2.png')}}">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 col-form-label">Image</label>
                                <div class="col-sm-7">
                                    <div class="form-group form-file-upload form-file-simple @if ($errors->has('image')) has-danger @endif">
                                        <input type="file" name="image" class="inputFileHidden" id="item-image-upload" accept="image/png, image/jpeg, image/jpg">
                                        <div class="input-group">
                                            <input type="text" class="form-control inputFileVisible" placeholder="Single File" id="item-image-input">
                                            <span class="input-group-btn">
                                                <button type="button" class="btn btn-fab btn-round btn-primary" id="item-image-button">
                                                    <i class="material-icons">attach_file</i>
                                                </button>
                                                <button type="button" class="btn btn-fab btn-round btn-danger" id="remove-item-image-button">
                                                    <i class="material-icons">delete</i>
                                                </button>
                                            </span>
                                        </div>
                                        @if ($errors->has('image'))
                                            <span class="material-icons form-control-feedback custom-error-cross">clear</span>
                                            @foreach ($errors->get('image') as $key => $error)
                                                <label id="image-error-{{$key}}" class="error" for="image"><strong>#{{++$key}}</strong> {{$error}}</label>
                                            @endforeach
                                        @endif
                                    </div>
                                </div>
                                <label class="col-sm-2 label-on-right ml-20">
                                    <code>optional</code>
                                </label>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 col-form-label" for="item-page-title">Title</label>
                                <div class="col-sm-7">
                                    <div class="form-group bmd-form-group @if ($errors->has('page_title')) has-danger @endif">
                                        <input class="form-control" type="text" id="item-page-title" name="page_title" required="true" value="{{old('page_title')}}">
                                        @if ($errors->has('page_title'))
                                            <span class="material-icons form-control-feedback custom-error-cross">clear</span>
                                            @foreach ($errors->get('page_title') as $key => $error)
                                                <label id="page_title-error-{{$key}}" class="error" for="page_title"><strong>#{{++$key}}</strong> {{$error}}</label>
                                            @endforeach
                                        @endif
                                    </div>
                                </div>
                                <label class="col-sm-2 label-on-right ml-20">
                                    <code>required</code>
                                </label>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 col-form-label" for="item-page-body">Content</label>
                                <div class="col-sm-7">
                                    <div class="form-group">
                                        <textarea class="form-control" id="item-page-body" name="page_body" required="true" rows="6">{{old('page_body')}}</textarea>
                                    </div>
                                </div>
                                <label class="col-sm-2 label-on-right ml-20">
                                    <code>required</code>
                                </label>
                            </div>
                        </div>
                        <div class="card-footer ml-auto mr-auto">
                            <button type="submit" id="add_item" class="btn btn-primary">Add Item</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js"></script>

    <script>

        function filePreview(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('.resize-image').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }

        $(document).ready(function () {

            let itemTextarea = null;

            itemTextarea = new FroalaEditor(
                '#item-page-body',
                {
                    heightMin: 100,
                }
            );

            let hideTextareaLogoInterval = setInterval(
                () => {
                    if (itemTextarea !== null)
                    {
                        $('a[id="logo"][href="https://froala.com/wysiwyg-editor"]').remove();
                        $('a[href="https://www.froala.com/wysiwyg-editor?k=u"]').parent('div').remove();
                        $('span.fr-placeholder').css('margin-top', '0px');
                        clearInterval(hideTextareaLogoInterval);
                    }
                },
                200
            );

            $('#item-image-button, #item-image-input').on('click', function () {
                $('#item-image-upload').trigger('click');
            });

            $('#item-image-upload').on('change', function () {
                var filename = $(this).val().split('\\').pop();
                $('#item-image-input').val(filename);
                filePreview(this);
            });

            $('#remove-item-image-button').on('click', function () {
                $('#item-image-upload').val('');
                $('#item-image-input').val('');
            });

            $('#redirect-to-items-index').on('click', function () {
                document.querySelector('#items-index').click();
            });

            $('label[id*="-error-"]').each(function (key, item) {
                $(item).removeClass('bmd-label-static');
            });

        });
    </script>
@endsection

resources/views/items/qrcode_pdf.blade.php
@extends('pdf_layout')

@section('css')
    <style>
        .text-center {
            text-align: center;
        }
    </style>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <table style="width:100%;">
                <tr>
                    <td align="center">
                        <img src="{{asset($item['qr_code_path'])}}">
                    </td>
                </tr>
            </table>
        </div>
    </div>
@endsection

resources/views/items/qrcode_with_info_pdf.blade.php
@extends('pdf_layout')

@section('css')
    <style>
        .text-center {
            text-align: center;
        }
    </style>
@endsection

@section('content')
    @include('items.qrcode_with_info_pdf_template', [
        'item' => $item,
    ])
@endsection

resources/views/items/qrcode_with_info_pdf_template.blade.php
<div class="row">
    <div class="col-12">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h4 class="text-center">{{$item['page_title']}}</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <table style="width:100%;">
                        <tr>
                            <td align="center">
                                <img src="{{asset($item['image_path'])}}" height="250px">
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    {!! $item['page_body'] !!}
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <table style="width:100%;">
                        <tr>
                            <td align="center">
                                <img src="{{asset($item['qr_code_path'])}}">
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/items/show_user.blade.php
@extends("user_layout")
@section("style")
    <style>
        .text-center-custom{
            text-align: center;
        }
        .text-left-custom{
            text-align: left;
        }
    </style>
@endsection

@section("content")
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="card card-nav-tabs text-center-custom">
                    <div class="card-header card-header-primary">
                        {{$item->page_title}}
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        <img src="{{asset($item->image_path)}}">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <div class="card-text text-left-custom">{!! $item->page_body !!}</div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        <img src="{{asset($item->qr_code_path)}}">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection